### ISSUE TITLE
Use backreferences in variables

### ISSUE THREAD

**Issue by HarHarLinks** [maubot/reactbot#16]
Building on the nitter sample, it would be pretty neat if we could do this:
```
templates:
    issue:
        type: m.room.message
        content:
            msgtype: m.text
            body: ${{URL}}

default_flags:
- ignorecase

rules:
    github:
        matches:
        - \#(\d+)
        template: issue
        variables:
            URL: https://github.com/my/project/issue/${{1}}
    jira:
        matches:
        - [^#](\d+)
        template: issue
        variables:
            URL: https://jira.atlassian.com/browse/ABC-${{1}}
```
