### ISSUE TITLE
[Feature request] Randomize between several reactions

### ISSUE THREAD

**Issue by boogewooge** [maubot/reactbot#5]
Maybe if there are multiple templates listed under the same rule, one of them gets picked randomly? I think this could be a fun spin, enables a lot of possibilities, too.

**Comment by tulir** [comment]
It's not the prettiest format, but it's already possible with jinja templates:

```yaml
rules:
  random:
    template: reaction
    matches:
    - hmm
    variables:
      reaction: "{{ ['🤔', '🧐'] | random }}"

**Comment by boogewooge** [comment]
Okay, I see. But how would you randomize between more complex message contents with this?

For example,

```
templates:
    test:
        type: m.room.message
        content: $${message}


rules:
    test:
        matches: [test]
        template: test
        variables:
            message: |-
                {{ [ { "msgtype": "m.notice", "body": "1!" }, { "msgtype": "m.notice" , "body": "2!" } ] | random }}
```

does not work for me.

**Comment by tulir** [comment]
You should use the random variable to only randomize the relevant part. For your example, just have "1!" and "2!" in the variable, and the msgtype and body in the template. Same for images: `mxc://` uri in the variable, rest of content in template

**Comment by tulir** [comment]
There's now a better syntax:

```yaml
rules:
    random:
        matches:
        - hmm
        template: reaction
        variables:
            reaction_choices:
            - 🤔
            - 🧐
            reaction: "{{ variables.reaction_choices | random }}"
```

To use it for randomizing arbitrary event content instead of single fields:

```yaml
templates:
    random:
        type: m.room.message
        content: "{{ choices | random | tojson }}"

rules:
    randomphoto:
        matches:
        - foo
        - bar
        template: random
        variables:
            choices:
            - msgtype: m.image
              url: mxc://example.com/foo
              body: foo.png
              info:
                  mimetype: image/png
                  w: 123
                  h: 123
            - msgtype: m.image
              url: mxc://example.com/bar
              body: bar.png
              info:
                  mimetype: image/png
                  w: 321
                  h: 321
```
