### ISSUE TITLE
multiple variable substitution does not work

### ISSUE THREAD

**Issue by spaetz** [maubot/reactbot#6]
Replacing multiple variables on the single line does not work in the template section. I *think* this is due to matching the locations of the variables once and then not updating them when a replacement of a variable with a different string length than the variable name shifts the string within the for loop.

https://github.com/maubot/reactbot/blob/821e670fd5d19f37ae26a7a9b3594a2131ba19c4/reactbot/template.py#L71

```
templates:
    swear_emote:
        type: m.room.message
        variables:
            relates_to: '{{event.sender}}'
        content:
            msgtype: m.emote
            body: takes $${0} $${relates_to} and stuffs them where the sun does not shine.
rules:
    swear_mobot:
        matches: ([\S]+) mobot
        template: swear_emote
```

`bad mobot` leads to` * Mobot takes bad $$@spaetz:matrix.debian.socialnd stuffs them where the sun does not shine.`
